CREATE TABLE employees.employees
(id INT NOT NULL AUTO_INCREMENT,
uuid VARCHAR(40) NOT NULL,
username VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(75) NOT NULL,
email VARCHAR(100) NOT NULL,
created DATETIME NOT NULL,
PRIMARY KEY (id)) DEFAULT CHARSET=utf8